apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: omdb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        de-app: omdb
    spec:
      restartPolicy: Always
      containers:
      - name: omdb
        image: gims.cyverse.org:5000/omdb-example
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: omdb-key
                key: API_KEY
        command: ["go-wrapper"]
        args:
          - run
          - --key
          - "$(API_KEY)"
        ports:
          - name: listen-port
            containerPort: 60000
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: omdb
spec:
  selector:
    de-app: omdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
